[package]
name = "coffe-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
chrono = "0.4.45"
clap = { version = "4.6.6", features = ["derive"] }
coffe-core = { version = "0.1.0", path = "../coffe-core" }
coffe-ipc = { version = "0.1.0", path = "../coffe-ipc" }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "net", "time", "signal", "io-util", "sync"] }

[[bin]]
name = "coffe"
path = "src/main.rs"
